model_selection:
  model:
    XGBClassifier:
      search_param_grid:
        n_estimators: [100, 300]
        max_depth: [3, 5, 7]
        learning_rate: [0.01, 0.1]
        subsample: [0.8, 1.0]
        colsample_bytree: [0.8, 1.0]
        scale_pos_weight: [1, 2]
        eval_metric: ['logloss']
        random_state: [1]
        n_jobs: [-1]

    GradientBoostingClassifier:
      search_param_grid:
        n_estimators: [100, 300]
        learning_rate: [0.01, 0.1]
        max_depth: [3, 5, 7]
        min_samples_split: [3, 5]
        min_samples_leaf: [2, 4]
        max_features: ['sqrt', 'log2']
        random_state: [1]

    KNNClassifier:
      search_param_grid:
        n_neighbors: [5, 7, 10, 15]
        weights: ['uniform', 'distance']
        metric: ['euclidean', 'manhattan']
        n_jobs: [-1]

    RandomForestClassifier:
      search_param_grid:
        n_estimators: [50, 100, 200]
        max_depth: [5, 10, 15]
        min_samples_split: [5, 7]
        min_samples_leaf: [2, 4]
        max_features: ['sqrt', 'log2']
        random_state: [1]
        n_jobs: [-1]